language: php

php:
  - '7.3'

install:
  - make install

before_script: 
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter 
- chmod +x ./cc-test-reporter 
- ./cc-test-reporter before-build

script:
  - make lint
  -  ./vendor/bin/phpunit tests --testsuite=unit

after_script: 
- vendor/bin/test-reporter
